/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as TeamSlugRouteImport } from './routes/team.$slug'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as ReservationReviewRouteImport } from './routes/reservation.review'
import { Route as AuthRegistrationRouteImport } from './routes/auth/registration'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoomsRoute,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RoomsRoute,
} as any)
const ReservationReviewRoute = ReservationReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ReservationRoute,
} as any)
const AuthRegistrationRoute = AuthRegistrationRouteImport.update({
  id: '/auth/registration',
  path: '/auth/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/rooms': typeof RoomsRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/reservation/review': typeof ReservationReviewRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/rooms/': typeof RoomsIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/reservation/review': typeof ReservationReviewRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/rooms': typeof RoomsIndexRoute
  '/team': typeof TeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/news': typeof NewsRoute
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRouteWithChildren
  '/rooms': typeof RoomsRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/registration': typeof AuthRegistrationRoute
  '/reservation/review': typeof ReservationReviewRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/team/$slug': typeof TeamSlugRoute
  '/rooms/': typeof RoomsIndexRoute
  '/team/': typeof TeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/profile'
    | '/reservation'
    | '/rooms'
    | '/team'
    | '/auth/login'
    | '/auth/registration'
    | '/reservation/review'
    | '/rooms/$slug'
    | '/team/$slug'
    | '/rooms/'
    | '/team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/profile'
    | '/reservation'
    | '/auth/login'
    | '/auth/registration'
    | '/reservation/review'
    | '/rooms/$slug'
    | '/team/$slug'
    | '/rooms'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/news'
    | '/profile'
    | '/reservation'
    | '/rooms'
    | '/team'
    | '/auth/login'
    | '/auth/registration'
    | '/reservation/review'
    | '/rooms/$slug'
    | '/team/$slug'
    | '/rooms/'
    | '/team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  NewsRoute: typeof NewsRoute
  ProfileRoute: typeof ProfileRoute
  ReservationRoute: typeof ReservationRouteWithChildren
  RoomsRoute: typeof RoomsRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegistrationRoute: typeof AuthRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof RoomsRoute
    }
    '/reservation/review': {
      id: '/reservation/review'
      path: '/review'
      fullPath: '/reservation/review'
      preLoaderRoute: typeof ReservationReviewRouteImport
      parentRoute: typeof ReservationRoute
    }
    '/auth/registration': {
      id: '/auth/registration'
      path: '/auth/registration'
      fullPath: '/auth/registration'
      preLoaderRoute: typeof AuthRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReservationRouteChildren {
  ReservationReviewRoute: typeof ReservationReviewRoute
}

const ReservationRouteChildren: ReservationRouteChildren = {
  ReservationReviewRoute: ReservationReviewRoute,
}

const ReservationRouteWithChildren = ReservationRoute._addFileChildren(
  ReservationRouteChildren,
)

interface RoomsRouteChildren {
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
}

const RoomsRouteChildren: RoomsRouteChildren = {
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsIndexRoute: RoomsIndexRoute,
}

const RoomsRouteWithChildren = RoomsRoute._addFileChildren(RoomsRouteChildren)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  NewsRoute: NewsRoute,
  ProfileRoute: ProfileRoute,
  ReservationRoute: ReservationRouteWithChildren,
  RoomsRoute: RoomsRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegistrationRoute: AuthRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
